version: '3'
services:
  service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - ../experiments/exp_padding_oracle/flag:/flag
    ports:
      - 1337:1337